// Command generate compiles the pinned CFF schema into Go validation rules.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"slices"
	"strings"
)

type schema struct {
	Title                string            `json:"title"`
	ID                   string            `json:"$id"`
	Schema               string            `json:"$schema"`
	Comment              string            `json:"$comment"`
	Ref                  string            `json:"$ref"`
	Description          string            `json:"description"`
	Examples             json.RawMessage   `json:"examples"`
	Default              json.RawMessage   `json:"default"`
	Type                 string            `json:"type"`
	Definitions          map[string]schema `json:"definitions"`
	Properties           map[string]schema `json:"properties"`
	AdditionalProperties *bool             `json:"additionalProperties"`
	Required             []string          `json:"required"`
	Enum                 []string          `json:"enum"`
	AnyOf                []schema          `json:"anyOf"`
	OneOf                []schema          `json:"oneOf"`
	Items                *schema           `json:"items"`
	MinItems             int               `json:"minItems"`
	UniqueItems          bool              `json:"uniqueItems"`
	MinLength            int               `json:"minLength"`
	MaxLength            int               `json:"maxLength"`
	Minimum              *int              `json:"minimum"`
	Maximum              *int              `json:"maximum"`
	Pattern              string            `json:"pattern"`
	Format               string            `json:"format"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	const fileMode = 0o644
	data, err := os.ReadFile("internal/schema/1.2.0.json")
	if err != nil {
		return err
	}
	var root schema
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&root); err != nil {
		return err
	}
	var out strings.Builder
	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n\npackage citation\n\nimport \"regexp\"\n\n")
	for _, name := range keys(root.Definitions) {
		code, err := compile(root.Definitions[name], root.Definitions)
		if err != nil {
			return fmt.Errorf("%s: %w", name, err)
		}
		fmt.Fprintf(&out, "var %s = %s\n\n", ruleName(name), code)
	}
	code, err := compile(root, root.Definitions)
	if err != nil {
		return err
	}
	fmt.Fprintf(&out, "var cff120 = %s\n", code)
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return err
	}
	return os.WriteFile("schema_generated.go", formatted, fileMode)
}

func keys[T any](m map[string]T) []string {
	result := make([]string, 0, len(m))
	for key := range m {
		result = append(result, key)
	}
	slices.Sort(result)
	return result
}

func ruleName(name string) string { return "cff120_" + strings.ReplaceAll(name, "-", "_") }

func compile(s schema, definitions map[string]schema) (string, error) {
	if s.Ref != "" {
		name, ok := strings.CutPrefix(s.Ref, "#/definitions/")
		if !ok {
			return "", fmt.Errorf("unsupported reference %q", s.Ref)
		}
		if _, ok := definitions[name]; !ok {
			return "", fmt.Errorf("unknown reference %q", s.Ref)
		}
		return ruleName(name), nil
	}
	if !slices.Contains([]string{"", "object", "array", "string", "number", "integer"}, s.Type) {
		return "", fmt.Errorf("unsupported type %q", s.Type)
	}
	if !slices.Contains([]string{"", "date", "uri"}, s.Format) {
		return "", fmt.Errorf("unsupported format %q", s.Format)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "&schemaRule{kind:%q, format:%q, minItems:%d, uniqueItems:%t, minLength:%d, maxLength:%d,", s.Type, s.Format, s.MinItems, s.UniqueItems, s.MinLength, s.MaxLength)
	if s.Minimum != nil {
		fmt.Fprintf(&b, "minimum:%d, hasMinimum:true,", *s.Minimum)
	}
	if s.Maximum != nil {
		fmt.Fprintf(&b, "maximum:%d, hasMaximum:true,", *s.Maximum)
	}
	if s.AdditionalProperties != nil {
		fmt.Fprintf(&b, "closed:%t,", !*s.AdditionalProperties)
	}
	if s.Pattern != "" {
		if _, err := regexp.Compile(s.Pattern); err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "pattern:regexp.MustCompile(%q),", s.Pattern)
	}
	fmt.Fprintf(&b, "required:%#v, enum:%#v,", s.Required, s.Enum)
	if s.Items != nil {
		code, err := compile(*s.Items, definitions)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "items:%s,", code)
	}
	if err := compileProperties(&b, s.Properties, definitions); err != nil {
		return "", err
	}
	alternatives := s.AnyOf
	if len(s.OneOf) != 0 {
		alternatives = s.OneOf
		b.WriteString("oneOf:true,")
	}
	if len(alternatives) != 0 {
		b.WriteString("alternatives:[]*schemaRule{")
		for _, option := range alternatives {
			code, err := compile(option, definitions)
			if err != nil {
				return "", err
			}
			b.WriteString(code + ",")
		}
		b.WriteString("},")
	}
	b.WriteByte('}')
	return b.String(), nil
}

func compileProperties(b *strings.Builder, properties, definitions map[string]schema) error {
	if len(properties) == 0 {
		return nil
	}
	b.WriteString("properties:map[string]*schemaRule{")
	for _, name := range keys(properties) {
		code, err := compile(properties[name], definitions)
		if err != nil {
			return err
		}
		fmt.Fprintf(b, "%q:%s,", name, code)
	}
	b.WriteString("},")
	return nil
}
